<?php

namespace AppBundle\Repository;

/**
 * OperationImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationImportRepository extends \Doctrine\ORM\EntityRepository
{
}
