# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.account_voter:
        class: AppBundle\Security\AccountVoter
        tags:
            - { name: security.voter }
        public: false
        autowire: true

    app.tag_voter:
        class: AppBundle\Security\TagVoter
        tags:
            - { name: security.voter }
        public: false
        autowire: true

    app.operation_voter:
        class: AppBundle\Security\OperationVoter
        tags:
            - { name: security.voter }
        public: false
        autowire: true

    app.doctrine.orm.query_extension.current_user:
        class: AppBundle\Doctrine\ORM\Extension\CurrentUserExtension
        public: false
        arguments:
            - '@api_platform.metadata.property.name_collection_factory'
            - '@api_platform.metadata.property.metadata_factory'
            - '@security.token_storage'
            - '@security.authorization_checker'
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }
