# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.account_voter:
        class: AppBundle\Security\AccountVoter
        tags:
            - { name: security.voter }
        public: false
        autowire: true

    app.tag_voter:
        class: AppBundle\Security\TagVoter
        tags:
            - { name: security.voter }
        public: false
        autowire: true

    app.operation_voter:
        class: AppBundle\Security\OperationVoter
        tags:
            - { name: security.voter }
        public: false
        autowire: true
