# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.operation_manager:
        class: AppBundle\Manager\OperationManager
        autowire: true

    app.account_voter:
        class: AppBundle\Security\AccountVoter
        tags:
            - { name: security.voter }
        public: false
        autowire: true

    app.tag_voter:
        class: AppBundle\Security\TagVoter
        tags:
            - { name: security.voter }
        public: false
        autowire: true

    app.operation_voter:
        class: AppBundle\Security\OperationVoter
        tags:
            - { name: security.voter }
        public: false
        autowire: true

    app.doctrine.orm.query_extension.current_user:
        class: AppBundle\Doctrine\ORM\Extension\CurrentUserExtension
        public: false
        arguments:
            - '@api_platform.metadata.property.name_collection_factory'
            - '@api_platform.metadata.property.metadata_factory'
            - '@security.token_storage'
            - '@security.authorization_checker'
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }

    operation.date_filter:
        parent:    'api_platform.doctrine.orm.date_filter'
        arguments: [ { date: ~ } ]
        tags:      [ { name: 'api_platform.filter', id: 'operation.date_filter' } ]

    operation.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'ipartial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'operation.search_filter' } ]

    operation.custom_list_filter:
        class: 'AppBundle\Filter\CustomListFilter'
        arguments:
            - '@doctrine'
            - '@request_stack'
            - '@logger'
            - { account.id: ~, tag.id: ~ }
        tags:
            - { name: 'api_platform.filter', id: 'operation.custom_list_filter' }
